package selenium;
 // Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
public class Lab4 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void caso1() {
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 1000000;
    int sueldo = 1500000;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = ahorro;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
    public void caso2() {    
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 4370250;
    int sueldo = 1500000;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = uf*35;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
    public void caso3() {
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 1000000;
    int sueldo = 1500001;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = ahorro;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0.0452*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
    public void caso4() {
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 4370250;
    int sueldo = 1500001;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = uf*150;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0.0452*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
    public void caso5() {
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 1000000;
    int sueldo = 2500001;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = ahorro;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0.0709*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
    public void caso6() {
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 4370250;
    int sueldo = 2500001;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = uf*150;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0.0709*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
    public void caso7() {
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 1000000;
    int sueldo = 3000001;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = ahorro;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0.1062*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
    public void caso8() {
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 4370250;
    int sueldo = 3000001;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = uf*150;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0.1062*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
    public void caso9() {
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 1000000;
    int sueldo = 4000001;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = ahorro;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0.1557*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
    public void caso10() {
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 4370250;
    int sueldo = 4000001;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = uf*150;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0.1557*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
    public void caso9() {
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 1000000;
    int sueldo = 6000001;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = ahorro;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0.2748*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
    public void caso10() {
    driver.get("https://devops-lab4.herokuapp.com/");
    int ahorro = 4370250;
    int sueldo = 6000001;
    vars.put("sueldo", sueldo);
    vars.put("ahorro", ahorro);
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys(vars.get("ahorro").toString());
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys(vars.get("sueldo").toString());
    driver.findElement(By.cssSelector(".btn")).click();
    vars.put("uf", driver.findElement(By.xpath("//tr[6]/td[2]")).getText());

    int uf = Integer.parseInt(vars.get("uf"));
    int diezPorCiento = uf*150;
    int saldo = ahorro - diezPorCiento;
    int impuesto = Math.round(0.2748*diezPorCiento);

    vars.put("diezPorCiento",diezPorCiento);
    vars.put("saldo",saldo);
    vars.put("impuesto",impuesto);

    assertThat(driver.findElement(By.xpath("//tr[1]/td[2]")).getText(), is("vars.get(\"diezPorCiento\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[2]/td[2]")).getText(), is("vars.get(\"saldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[3]/td[2]")).getText(), is("vars.get(\"impuesto\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[4]/td[2]")).getText(), is("vars.get(\"sueldo\").toString()"));
    assertThat(driver.findElement(By.xpath("//tr[5]/td[2]")).getText(), is("vars.get(\"ahorro\").toString()"));
  }
  
}
