package selenium;
 // Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;
public class Lab4 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver","drivers/chromedriver");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void Lab4() throws InterruptedException {
    driver.get("https://devops-lab4.herokuapp.com/");
    driver.manage().window().setSize(new Dimension(1792, 1120));
    driver.findElement(By.id("saldo")).click();
    driver.findElement(By.id("saldo")).sendKeys("10000000");
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).sendKeys("1600000");
    driver.findElement(By.cssSelector(".btn")).click();
    
    TimeUnit.SECONDS.sleep(2);

    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("saldo")).sendKeys("460000000");
    driver.findElement(By.id("sueldo")).click();
    driver.findElement(By.id("sueldo")).click();
    {
      WebElement element = driver.findElement(By.id("sueldo"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("sueldo")).sendKeys("0");
    driver.findElement(By.cssSelector(".btn")).click();

    TimeUnit.SECONDS.sleep(2);
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("saldo")).sendKeys("35000000");
    driver.findElement(By.cssSelector(".form-outline:nth-child(2)")).click();
    driver.findElement(By.cssSelector("body")).click();
    driver.findElement(By.id("sueldo")).sendKeys("1800000");
    driver.findElement(By.cssSelector(".btn")).click();
  }
}
